Provide binary compatible API for Rust project settings
Before these changes there was only one way to change almost all properties of `RustProjectSettingsService`:
get `data`, create new one with necessary changes and set new instance to the settings.
Because of `RustProjectSettingsService.Data` is immutable, you have to create new instance via constructor
or `copy` method.
But any changes in class lead to `java.lang.NoSuchMethodError` in external code
because signatures of constructor and `copy` method are changing accordingly

These changes provide setter for each property (i.e. make each property mutable)
It should be enough to change any property and do not touch `RustProjectSettingsService.Data` class