GRD: update gradle-intellij-plugin to 1.5.2
It should fix the bootstrap error caused by `java.lang.NoClassDefFoundError: com/intellij/openapi/util/SystemInfoRt` with latest 2022.1 builds during `runIde` task